### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [ItsLaro/Teleroid#1]
It looks like your video walkthrough doesn't seem to show one of the required stories wherein the current signed in user is persisted across app restarts. Can you update this and resubmit?

**Comment by ivanreor** [comment]
Hello there,

My apologies. It looks like the original video lost a few seconds there at the end when I converted it to a GIF. I have added the revised GIF in full length which now properly shows the persistant session. The project has been resubmitted. 

Thank you! 😁

**Comment by codepathreview** [comment]
Nice work, Ivan. We put together a detailed Project 4 Feedback Guide here: (http://courses.codepath.org/snippets/android_university_fast_track/feedback_guides/project_4_feedback) which covers the most common issues with this project. Read through the feedback guide point-by-point to determine how you could improve your submission.

We hope you enjoyed the course and learned a lot in the process and look forward to see what you build for your final internship project!
 
/cc @codepathreview
